spring:
  application:
    name: remsfal-prioritization-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:39092}

    consumer:
      group-id: ${CONSUMER_GROUP:remsfal-prioritization-service}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all

remsfal:
  kafka:
    topics:
      in: ${TOPIC_IN:tickets.incoming}
      out: ${TOPIC_OUT:tickets.prioritized}
